spring.application.name=account-service
server.port=8012

spring.datasource.url=jdbc:h2:mem:accountdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=account
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true

management.endpoints.web.exposure.include=health,metrics
management.metrics.export.simple.enabled=true

# Distributed Tracing Configuration
spring.sleuth.trace-id128=true
spring.sleuth.sampler.probability=1.0

# Logging Configuration
logging.level.root=INFO
logging.level.com.account_service=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] [%X{traceId}] %-5level %logger{36} - %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] [%X{traceId}] %-5level %logger{36} - %msg%n
